version: "3.3"
networks:
   gamein:
     external: true
     
services:
  dashboard:
    build: .
    container_name: dashboard
    restart: always
    ports:
      - 8082:8080
    networks:
      - gamein
    environment:
      - spring.datasource.url=jdbc:postgresql://pgsql/gamein
      - spring.datasource.username=gamein
      - spring.datasource.password=gamein123
