version: "3.3"
networks:
   gamein:
     external: true
     
services:
  dashboard:
    image: registry.dariasystem.com/gamein/dashboard:dev
    container_name: dashboard
    restart: always
    ports:
      - 8082:8080
    networks:
      - gamein
    environment:
      - spring.datasource.url=jdbc:postgresql://192.168.0.223:5432/gamein-2022-new
      - spring.datasource.username=gamein
      - spring.datasource.password=gamein123
      - live.data.url=http://192.168.0.222:8083/websocket/api/notify


  dashboard-1:
    image: registry.dariasystem.com/gamein/dashboard:dev
    container_name: dashboard-1
    restart: always
    ports:
      - 9082:8080
    networks:
      - gamein
    environment:
      - spring.datasource.url=jdbc:postgresql://192.168.0.223:5432/gamein-2022-new
      - spring.datasource.username=gamein
      - spring.datasource.password=gamein123
      - live.data.url=http://192.168.0.222:8083/websocket/api/notify
