
name: deploy dashboard

on:
  push:
    branches: [ "master" ]

jobs:
  build-dashboard:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              ls -la
              docker build -t dashboard:dev .
              docker rm -f dashboard      
              docker-compose up  -d dashboard
              sleep 20
              docker rm -f dashboard-1
              docker-compose up  -d dashboard-1
              docker-compose ps
