
name: deploy dashboard

on:
  push:
    branches: [ "master" ]

jobs:
  build-dashboard:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              ls -la
              docker rm -f dashboard      
              docker-compose up --build -d
              docker-compose ps
