
name: deploy dashboard

on:
  push:
    branches: [ "master" ]

jobs:
#   check-code:
#     runs-on: [self-hosted, linux]
#     steps:
#       - uses: actions/checkout@master
#       - run: |
#              export PATH=$PATH:/opt/gradle/gradle-8.1.1/bin
#              echo $PATH
#              gradle -v
#              gradle  --stacktrace sonar \
#               -Dsonar.projectKey=dashboard \
#               -Dsonar.projectName='dashboard' \
#               -Dsonar.host.url=http://192.168.0.202:9000 \
#               -Dsonar.token=sqp_ae9abc486797b516f685843f5b9575e048ccaba4
        
        


  build-dashboard:
    #needs: check-code
    runs-on: [app]
    steps:
      - uses: actions/checkout@master
      - run: |
              docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              docker build -t registry.dariasystem.com/gamein/dashboard:dev .
              docker push registry.dariasystem.com/gamein/dashboard:dev
 
 
  deploy-dashboard:
    needs: build-dashboard
    runs-on: [app]
    steps:
      - uses: actions/checkout@master
      - run: | 
              docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              docker pull registry.dariasystem.com/gamein/dashboard:dev
              docker rm -f dashboard      
              docker-compose up  -d dashboard
              sleep 10
              docker compose ps
              
              
  deploy-dashboard-1:
    needs: build-dashboard
    runs-on: [app-1]
    steps:
      - uses: actions/checkout@master
      - run: | 
              docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              docker pull registry.dariasystem.com/gamein/dashboard:dev
              docker rm -f dashboard-1
              docker compose up  -d dashboard-1
              sleep 10
              docker compose ps
