
name: deploy dashboard

on:
  push:
    branches: [ "master" ]

jobs:
  check-code:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              gradle build -x test --stacktrace sonar \
              -Dsonar.projectKey=dashboard \
              -Dsonar.projectName='dashboard' \
              -Dsonar.host.url=http://192.168.0.202:9000 \
              -Dsonar.token=sqp_ae9abc486797b516f685843f5b9575e048ccaba4
        
        


  build-dashboard:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              ls -la
              docker build -t dashboard:dev .
              docker rm -f dashboard      
              docker-compose up  -d dashboard
              sleep 20
              docker rm -f dashboard-1
              docker-compose up  -d dashboard-1
              docker-compose ps
